/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  WebGoogleMapsOptions,
} from './types/web-google-maps/web-google-maps-options';
import {
  WebGoogleMapsStyle,
} from './types/web-google-maps/web-google-maps-style';
import {
  WebGoogleMapsCircle,
} from './types/web-google-maps/web-google-maps-circle';
import {
  WebGoogleMapsMarkers,
} from './types/web-google-maps/web-google-maps-markers';


export namespace Components {

  interface WebGoogleMaps {
    'apiKey': string;
    'circles': WebGoogleMapsCircle[];
    'lat': number;
    'lng': number;
    'mapStyle': WebGoogleMapsStyle;
    'markers': WebGoogleMapsMarkers;
    'options': WebGoogleMapsOptions;
  }
  interface WebGoogleMapsAttributes extends StencilHTMLAttributes {
    'apiKey'?: string;
    'circles'?: WebGoogleMapsCircle[];
    'lat'?: number;
    'lng'?: number;
    'mapStyle'?: WebGoogleMapsStyle;
    'markers'?: WebGoogleMapsMarkers;
    'onGoogleMapsApiKeyLoaded'?: (event: CustomEvent<void>) => void;
    'options'?: WebGoogleMapsOptions;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WebGoogleMaps': Components.WebGoogleMaps;
  }

  interface StencilIntrinsicElements {
    'web-google-maps': Components.WebGoogleMapsAttributes;
  }


  interface HTMLWebGoogleMapsElement extends Components.WebGoogleMaps, HTMLStencilElement {}
  var HTMLWebGoogleMapsElement: {
    prototype: HTMLWebGoogleMapsElement;
    new (): HTMLWebGoogleMapsElement;
  };

  interface HTMLElementTagNameMap {
    'web-google-maps': HTMLWebGoogleMapsElement
  }

  interface ElementTagNameMap {
    'web-google-maps': HTMLWebGoogleMapsElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
